### ISSUE TITLE
Missing distribution or build instructions

### ISSUE THREAD

**Issue by frankkoornstra** [gertschouten/kafka-connect-jdbc-flatten#1]
I was glad to run into this project because it seems to do exactly what we need so thanks for all your efforts so far :slightly_smiling_face: 

I'm trying to incorporate the connector in our project but seem to have trouble either (a) finding  the jar somewhere on a public Maven repo, or (b) building it from scratch. It would be really nice if the repo's Readme contained a hint for either of these and how to build it, what environment is needed, etc. I concluded from the Confluent docs that Java 1.8 is the target platform.

When I'm building it, I'm using the following Dockerfile so I have a clean build environment:
```Dockerfile
FROM adoptopenjdk/maven-openjdk8:latest AS builder

USER root

RUN mkdir /project \
    && cd /project \
    && curl -L https://github.com/gertschouten/kafka-connect-jdbc-flatten/archive/2474700dab4345cd92d2d14ddc035e43875fbfa4.tar.gz | tar -xz \
    && cd kafka-connect-jdbc-flatten*
```

And then run into the following
```
root@e38cc4f8d195:/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4# ls
config  docs  Jenkinsfile  LICENSE  licenses  licenses.html  logos  NOTICE  pom.xml  README.md  readme_pics  src  version.txt
root@e38cc4f8d195:/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4# mvn package
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/common-parent/5.5.0/common-parent-5.5.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.kafka:connect-api:jar -> version (?) vs 2.5.0 @ line 165, column 21
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-jdbc_flatten:5.5.0: Could not transfer artifact io.confluent:common-parent:pom:5.5.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 22, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-connect-jdbc_flatten:5.5.0 (/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-jdbc_flatten:5.5.0: Could not transfer artifact io.confluent:common-parent:pom:5.5.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 22, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

I've searched for the non-resolvable parent POM but most of those issues where from before the public Confluent Maven repo. Am I missing something?

**Comment by gertschouten** [comment]
Hi Frank, I see that the log reports an attempt to download from maven central, which gives 404 on fetching: https://repo.maven.apache.org/maven2/io/confluent/common-parent/5.5.0/common-parent-5.5.0.pom

Rather it should try to access http://packages.confluent.io/maven/io/confluent/common/5.5.0/common-5.5.0.pom (confluent repo).

You'll probably get a step further when you set this Url in pom.xml of the kafka-connect-jdbc-flatten project as the <pluginRepository><url> regarding confluent plugin repository.

Let me know if this helps.

Please also be aware that if you succefully build the connector, the target connector jar file needs to be added to the kafka connect image as a plugin in the plugin path: plugin.path.

Are you planning on using for example this kafka connect image? 
https://hub.docker.com/r/confluentinc/cp-kafka-connect

**Comment by frankkoornstra** [comment]
I saw that url as a variable in the POM and from what I understand from the POM (I only worked with Gradle so far) is that it also gets a default value pointing to the Confluent maven repo. I also tried to explicitly define the repo url as follows but with the same result:
```
root@f950182961ab:/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4# ls
config  docs  Jenkinsfile  LICENSE  licenses  licenses.html  logos  NOTICE  pom.xml  README.md  readme_pics  src  version.txt
root@f950182961ab:/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4# mvn -Dconfluent.maven.repo=http://packages.confluent.io/ package
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/common-parent/5.5.0/common-parent-5.5.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.kafka:connect-api:jar -> version (?) vs 2.5.0 @ line 165, column 21
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-jdbc_flatten:5.5.0: Could not transfer artifact io.confluent:common-parent:pom:5.5.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 22, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
...
```

I don't think I can create a cleaner build environment than this with a fresh Docker image only downloading this repo's source files so I'm trying to discover what's different in your/the maintainer's build environment that does make this succeed.

>Please also be aware that if you succefully build the connector, the target connector jar file needs to be added to the kafka connect image as a plugin in the plugin path: plugin.path.
>
>Are you planning on using for example this kafka connect image?
>https://hub.docker.com/r/confluentinc/cp-kafka-connect

Thanks for the tip. We're building our own Kafka Connect image based on Confluent's base image with a few tweaks.

**Comment by gertschouten** [comment]
I see.

Try these possibilities: https://github.com/confluentinc/kafka-connect-hdfs/issues/311

a. mvn clean install -Dconfluent.maven.repo=https://packages.confluent.io/maven

or ... notice the path /maven... which you omitted as your log says mvn -Dconfluent.maven.repo=http://packages.confluent.io/
without the maven path

b. http://packages.confluent.io/maven/

**Comment by frankkoornstra** [comment]
I tried the `-D...` option with the path, without the path, with https, without https... all the same result. 

If I replace the variable in the `repositories` section with a static value it works but how is it working for you/other maintainers but not in a clean environment like a fresh Docker container? My assumption here is that cloning the project, in the right environment, should be enough to run `mvn package` or `mvn clean install`.

Anyway, should I open a PR to this repo for the change with the static value?

**Comment by frankkoornstra** [comment]
Also now further in the build I run into the following issue:
```
...
#6 278.7 Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (13 kB at 9.0 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.21/plexus-utils-3.0.21.jar (245 kB at 159 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar (3.8 MB at 1.9 MB/s)
#6 279.4 [INFO] Executing: /bin/sh -c cd '/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4' && 'git' 'rev-parse' '--verify' 'HEAD'
#6 279.4 [INFO] Working directory: /project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4
#6 279.5 [INFO] ------------------------------------------------------------------------
#6 279.5 [INFO] BUILD FAILURE
#6 279.5 [INFO] ------------------------------------------------------------------------
#6 279.5 [INFO] Total time:  04:37 min
#6 279.5 [INFO] Finished at: 2020-10-26T16:14:53Z
#6 279.5 [INFO] ------------------------------------------------------------------------
#6 279.5 [ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project kafka-connect-jdbc_flatten: Cannot get the revision information from the scm repository : 
#6 279.5 [ERROR] Exception while executing SCM command.: Error while executing command. Error while executing process. Cannot run program "git" (in directory "/project/kafka-connect-jdbc-flatten-2474700dab4345cd92d2d14ddc035e43875fbfa4"): error=2, No such file or directory
```

So I also need `git` installed. It'd be nice if these requirements can be documented in the readme. It's quite painful to go through this stumbling every other step.

**Comment by frankkoornstra** [comment]
For future reference: this is the Dockerfile I use to build the project successfully

```Dockerfile
FROM adoptopenjdk/maven-openjdk11:latest AS builder

USER root

RUN apt-get update \
    && apt-get install -y git

RUN cd / \
    && git clone https://github.com/gertschouten/kafka-connect-jdbc-flatten.git \
    && cd kafka-connect-jdbc-flatten \
    && git checkout 2474700dab4345cd92d2d14ddc035e43875fbfa4 \
    && sed -i 's/\${confluent.maven.repo}/http:\/\/packages.confluent.io\/maven\//g' pom.xml \
    && mvn clean install -DskipTests

WORKDIR /kafka-connect-jdbc-flatten
```

**Comment by gertschouten** [comment]
I was reproducing your steps locally here. There is a bunch of plugins that got inherited from the forked confluent jdbc connector in the maven setup. 

Also for me -DskipTests was necessary, due to dependencies on integration tests towards mysql and others.
I come to the same result when installing git and as you noticed, use the http instead of https url of confluent maven repo.

I will put a reference to your building steps here in the readme for others to use. I guess the majority downloads the ready-built zip from confluent hub.

This was valuable info..I thank you for that.
Let me know if you have any other remarks.

**Comment by frankkoornstra** [comment]
I think there were simply a lot of assumptions in the process, which is understandable if you setup the project from the start but makes it a little hard for outsiders to get involved :slightly_smiling_face:

In my experience, the best way to get all those assumptions in the open is to setup a CI/CD pipeline. It will force you to create a clean build environment and others can look at it as an example. Github offers Actions for free to OSS projects so that might help. Final step in that CI/CD pipeline could also be to push the JAR to Github Packages so others can simply make use of that.

Thanks again for all your effort in this project!
