### ISSUE TITLE
Use Confluent JDBC as dependancy instead of source code

### ISSUE THREAD

**Issue by jchanaud** [gertschouten/kafka-connect-jdbc-flatten#5]
Hi,

We are running a Connect Cluster with a more recent version of https://github.com/confluentinc/kafka-connect-jdbc
than the one you are based on.
Interestingly, when we list the connectors classes available, we see this : 
````console
curl http://connect-cluster:8083/connector-plugins
[
  {"class":"io.confluent.connect.jdbc.JdbcSinkConnector_Flatten","type":"sink","version":"5.5.0"},
  {"class":"io.confluent.connect.jdbc.JdbcSourceConnector","type":"source","version":"5.5.0"},
  {"class":"io.confluent.connect.jdbc.JdbcSourceConnector","type":"source","version":"10.0.2"}
]
````
I believe it will cause issues if we deploy a config that depends on 10.0.2.
Kafka Connect doesn't seem to garantee which version of the class will be called.

https://docs.confluent.io/kafka-connect-jdbc/current/changelog.html
 
I see multiple ways to fix this and I would be fine making a PR myself.
1. Rename the class or package of the confluent Class on your side
2. Use Confluent code as a build dependancy assuming you did'nt change anything to their code. This would require to place your jar in the same classloader context as the Confluent jar, not sure it's reasonable

What's your opinion on this matter ?

**Comment by gertschouten** [comment]
Hi twobeeb.

Thanks for reaching out. 
You are right. 
Let me put both the Source and the Sink connector class in a non-confluent package.
I can do this later these evening and merge it in subsequently.

**Comment by gertschouten** [comment]
Hi twobeeb,

Now I hope they are no longer conflicting:
no.norsktipping.kafka.connect.jdbc.connector.JdbcSinkConnector_Flatten
no.norsktipping.kafka.connect.jdbc.connector.JdbcSourceConnector_Flatten

Can you report back if you have had time to check and it's OK. And when it is not OK off course :-)

**Comment by jchanaud** [comment]
Confirmed 👍  : 
````console
[root@carsfkc01 confluent-hub-components]# curl localhost:8083/connector-plugins
[
  {"class":"io.confluent.connect.jdbc.JdbcSinkConnector","type":"sink","version":"10.0.2"},
  {"class":"io.confluent.connect.jdbc.JdbcSourceConnector","type":"source","version":"10.0.2"},
  {"class":"no.norsktipping.kafka.connect.jdbc.connector.JdbcSinkConnector_Flatten","type":"sink","version":"5.5.1"},
  {"class":"no.norsktipping.kafka.connect.jdbc.connector.JdbcSourceConnector_Flatten","type":"source","version":"5.5.1"}
  ...
]
````
I did build your jar from github and deployed it locally. I'm currently asking my project teams to redeploy their configuration (rename the class).
Also, any chance you could release on confluent hub ? that's my prefered installation method for production connector classes

**Comment by gertschouten** [comment]
Nice. 
Okay, I mailed confluent hub admin to ask if he can get the hub in synch with the repo.
Not sure when he is able to synch, but I guess we will see it when it is done.
Have a nice evening.
And let me know if there pops anything else.

**Comment by jchanaud** [comment]
Hello @gertschouten,

Any update on the 5.5.1 release on Confluent Hub ?

**Comment by gertschouten** [comment]
Hi Julien,

Friday the 26th November 2021 I mailed: confluent-hub@confluent.io

##############################
Hi good evening,

Could you synch the connector… 
https://www.confluent.io/hub/norsktipping/kafka-connect-jdbc_flatten
…from its repo..
https://github.com/gertschouten/kafka-connect-jdbc-flatten

It is lagging a few commits behind and the source code link from confluent hub was misconfigured.

Hope to hear from you,
Thanks

Vennlig hilsen

Gert J. Schouten
###############################

The folks there are busy I guess. I also previously asked them to correct the documentation link a couple of times. But unfortunately no movement.
Can you send them a mail from your end too......let's see if that helps?

Something else. I am soon going to ask verification from Confluent on this new connector as well:
https://github.com/gertschouten/kafka-connect-jdbc-event-store
Hopefully they'll accept it into their verification program towards Confluent Hub as well.
Have a look and see if it might be interesting for any of your use cases as well.
